using System.Collections.Generic;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Backpack.Viewer.SourceGeneration;

[Generator(LanguageNames.CSharp)]
public sealed class DependencyPropertyGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName = "Backpack.Viewer.DependencyPropertyAttribute`1";

    private const string AttributeSource =
        "// <auto-generated/>\n" +
        "#nullable enable\n" +
        "namespace Backpack.Viewer\n" +
        "{\n" +
        "    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]\n" +
        "    internal sealed class DependencyPropertyAttribute<T> : global::System.Attribute\n" +
        "    {\n" +
        "        public DependencyPropertyAttribute(string name) => Name = name;\n" +
        "        public string Name { get; }\n" +
        "        public object? DefaultValue { get; set; }\n" +
        "        public string? PropertyChangedCallbackName { get; set; }\n" +
        "        public bool NotNull { get; set; }\n" +
        "    }\n" +
        "}\n";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("DependencyPropertyAttribute.g.cs", AttributeSource));

        IncrementalValuesProvider<(string? HintName, string? Source)> provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeMetadataName,
                static (node, _) => node is ClassDeclarationSyntax,
                Transform)
            .Where(static s => s.HintName is not null);

        context.RegisterSourceOutput(provider, static (spc, source) =>
            spc.AddSource(source.HintName!, source.Source!));
    }

    private static (string? HintName, string? Source) Transform(GeneratorAttributeSyntaxContext context, CancellationToken token)
    {
        if (context.TargetSymbol is not INamedTypeSymbol type)
        {
            return default;
        }

        string ownerFqn = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        StringBuilder members = new();
        foreach (AttributeData attribute in context.Attributes)
        {
            token.ThrowIfCancellationRequested();
            EmitProperty(members, ownerFqn, attribute);
        }

        if (members.Length == 0)
        {
            return default;
        }

        string ns = type.ContainingNamespace.IsGlobalNamespace ? string.Empty : type.ContainingNamespace.ToDisplayString();
        string hintName = ownerFqn.Substring("global::".Length).Replace('<', '_').Replace('>', '_').Replace(',', '_') + ".DependencyProperties.g.cs";
        return (hintName, WrapType(ns, type.Name, members.ToString()));
    }

    private static void EmitProperty(StringBuilder members, string ownerFqn, AttributeData attribute)
    {
        if (attribute.AttributeClass is not { TypeArguments.Length: 1 } attrClass)
        {
            return;
        }

        if (attribute.ConstructorArguments.Length < 1 || attribute.ConstructorArguments[0].Value is not string name || name.Length == 0)
        {
            return;
        }

        ITypeSymbol propertyType = attrClass.TypeArguments[0];
        string typeName = propertyType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        string? defaultExpr = null;
        string? callbackName = null;
        bool notNull = false;

        foreach (KeyValuePair<string, TypedConstant> arg in attribute.NamedArguments)
        {
            switch (arg.Key)
            {
                case "DefaultValue":
                    defaultExpr = FormatConstant(arg.Value);
                    break;
                case "PropertyChangedCallbackName":
                    callbackName = arg.Value.Value as string;
                    break;
                case "NotNull":
                    notNull = arg.Value.Value is true;
                    break;
            }
        }

        string propType = propertyType.IsReferenceType && !notNull ? typeName + "?" : typeName;
        string defaultValue = defaultExpr ?? "default(" + typeName + ")";
        string metadata = callbackName is null
            ? "new global::Microsoft.UI.Xaml.PropertyMetadata(" + defaultValue + ")"
            : "new global::Microsoft.UI.Xaml.PropertyMetadata(" + defaultValue + ", " + callbackName + ")";

        members
            .Append("    public static readonly global::Microsoft.UI.Xaml.DependencyProperty ").Append(name)
            .Append("Property = global::Microsoft.UI.Xaml.DependencyProperty.Register(\"").Append(name)
            .Append("\", typeof(").Append(typeName).Append("), typeof(").Append(ownerFqn).Append("), ")
            .Append(metadata).Append(");\n");

        members
            .Append("    public ").Append(propType).Append(' ').Append(name).Append(" { get => (")
            .Append(propType).Append(")GetValue(").Append(name).Append("Property); set => SetValue(")
            .Append(name).Append("Property, value); }\n\n");
    }

    private static string FormatConstant(TypedConstant constant)
    {
        if (constant.IsNull)
        {
            return "null";
        }

        switch (constant.Kind)
        {
            case TypedConstantKind.Enum:
                return "(" + constant.Type!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + ")" + SymbolDisplay.FormatPrimitive(constant.Value!, false, false);
            case TypedConstantKind.Type:
                return constant.Value is ITypeSymbol type
                    ? "typeof(" + type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + ")"
                    : "null";
            case TypedConstantKind.Primitive:
                return SymbolDisplay.FormatPrimitive(constant.Value!, true, false) ?? "null";
            default:
                return "null";
        }
    }

    private static string WrapType(string ns, string className, string members)
    {
        StringBuilder sb = new();
        sb.Append("// <auto-generated/>\n#nullable enable\n");

        bool hasNamespace = ns.Length > 0;
        if (hasNamespace)
        {
            sb.Append("namespace ").Append(ns).Append("\n{\n");
        }

        sb.Append("partial class ").Append(className).Append("\n{\n").Append(members).Append("}\n");

        if (hasNamespace)
        {
            sb.Append("}\n");
        }

        return sb.ToString();
    }
}
