using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;

namespace Backpack.Viewer.SourceGeneration;

[Generator(LanguageNames.CSharp)]
public sealed class LocalizedKeysGenerator : IIncrementalGenerator
{
    private static readonly Regex DataName = new("<data\\s+name=\"([^\"]+)\"", RegexOptions.Compiled);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var resw = context.AdditionalTextsProvider
            .Where(static f => f.Path.EndsWith("Resources.resw", StringComparison.OrdinalIgnoreCase))
            .Collect();

        context.RegisterSourceOutput(resw, static (spc, files) =>
        {
            var keys = new SortedSet<string>(StringComparer.Ordinal);
            foreach (var file in files)
            {
                var text = file.GetText(spc.CancellationToken)?.ToString();
                if (string.IsNullOrEmpty(text))
                {
                    continue;
                }

                foreach (Match match in DataName.Matches(text!))
                {
                    var name = match.Groups[1].Value;
                    if (IsValidIdentifier(name))
                    {
                        keys.Add(name);
                    }
                }
            }

            if (keys.Count == 0)
            {
                return;
            }

            var sb = new StringBuilder();
            sb.Append("// <auto-generated/>\n#nullable enable\n");
            sb.Append("namespace Backpack.Viewer.Localization\n{\n");
            sb.Append("    internal static class SR\n    {\n");
            foreach (var key in keys)
            {
                sb.Append("        public static string ").Append(key).Append(" => Localized.Get(\"").Append(key).Append("\");\n");
            }

            sb.Append("    }\n}\n");
            spc.AddSource("SR.g.cs", sb.ToString());
        });
    }

    private static bool IsValidIdentifier(string s)
    {
        if (s.Length == 0 || !(char.IsLetter(s[0]) || s[0] == '_'))
        {
            return false;
        }

        foreach (var c in s)
        {
            if (!(char.IsLetterOrDigit(c) || c == '_'))
            {
                return false;
            }
        }

        return true;
    }
}